<--Première étape : Consultation des tables systèmes-->
<--1)-->
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PROF';
<--2)-->
SELECT OBJECT_NAME FROM USER_OBJECT WHERE OBJECT_TYPE = 'FUCNTION' OR OBJECT_TYPE = 'PROCEDURE';
<--3)-->
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS;
<--4)-->
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS JOIN USER_TAB_COLUMNS ON USER_CONSTRAINTS.TABLE_NAME = USER_TAB_COLUMNS.TABLE_NAME WHERE DATA_TYPE = 'NUMBER';
<--5)-->
SELECT CONSTRAINT_NAME, COLUMN_NAME FROM USER_CONSTRAINTS JOIN USER_TAB_COLUMNS ON USER_CONSTRAINTS.TABLE_NAME = USER_TAB_COLUMNS.TABLE_NAME WHERE DATA_TYPE = 'NUMBER';
<--6)-->
SELECT CI.CONSTRAINT_NAME, COl.COLUMN_NAME,COL.DATA_TYPE FROM USER_CONSTRAINTS CI, USER_TAB_COLUMNS COL WHERE CI.TABLE_NAME = COL.TABLE_NAME AND CI.COLUMN_NAME = COL.TABLE_NAME AND CI.TABLE_NAME IN (SELECT TABLE_NAME FROM USER_TAB_COLUMNS C WHERE C.DATA_TYPE = 'NUMBER');
<--7)-->
SELECT CONSTRAINT_NAME,SEARCH_CONDITION FROM USER_CONTRAINTS WHERE CONSTRAINT_TYPE = 'C';
<--8)-->
SELECT R1.COLUMN_NAME,R1.TABLE_NAME,R2.COLUMN_NAME,R2.TABLE_NAME FROM USER_TAB_COLUMNS R1, USER_TAB_COLUMNS R2 WHERE R1.COLUMN_NAME = R2.COLUMN_NAME AND R1.TABLE_NAME != R2.TABLE_NAME;
<--9)-->

<--Deuxième étape : Création et manipulation de vues-->
<--10)-->
CREATE VIEW PROF_INFO2
AS
  SELECT NUM_PROF,NOM_PROF,PRENOM_PROF
  FROM PROF,ENSEIGNT,ETUDIANT
  WHERE PROF.NUM_PROF = ENSEIGNT.NUM_PROF AND ENSEIGNT.NUM_ET = ETUDIANT.NUM_ET AND ANNEE = 2;
<--11)-->

<--12)-->

<--13)-->
CREATE VIEW VERIF_ENS
AS
  SELECT  *
  FROM    ENSEIGNT
  WHERE   CODE      IN (SELECT CODE      FROM MODULE)
  AND     NUM_PROF  IN (SELECT NUM_PROF  FROM PROF)
  AND     NUM_ET    IN (SELECT NUM_ET    FROM ETUDIANT)
  
WITH CHECK OPTION;
<--14)-->
CREATE VIEW VERIF_MOD
AS
  SELECT *
  FROM MODULE
  WHERE CODE NOT IN (SELECT CODEPERE   FROM MODULE)
  AND   CODE NOT IN (SELECT CODE       FROM ENSEIGNT)
  AND   CODE NOT IN (SELECT CODE       FROM NOTATION)
  
WITH CHECK OPTION;
<--Troisième étapes : Gestion des privilèges d'accèes aux données-->>
<--15)-->
GRANT SELECT ON TABLE ETUDIANT TO PUBLIC;
<--17)-->
GRANT SELECT,UPDATE ON TABLE PROF TO ETxxxx;
<--Quatrième étape : Développement en PL/SQL-->
<--18)-->

<--19)-->
