<--1)-->
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PROF';
<--2)-->
SELECT OBJECT_NAME FROM USER_OBJECT WHERE OBJECT_TYPE = 'FUCNTION' OR OBJECT_TYPE = 'PROCEDURE';
<--3)-->
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS;
<--4)-->
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS JOIN USER_TAB_COLUMNS ON USER_CONSTRAINTS.TABLE_NAME = USER_TAB_COLUMNS.TABLE_NAME WHERE DATA_TYPE = 'NUMBER';
<--5)-->
SELECT CONSTRAINT_NAME, COLUMN_NAME FROM USER_CONSTRAINTS JOIN USER_TAB_COLUMNS ON USER_CONSTRAINTS.TABLE_NAME = USER_TAB_COLUMNS.TABLE_NAME WHERE DATA_TYPE = 'NUMBER';
<--6)-->
SELECT CI.CONSTRAINT_NAME, COl.COLUMN_NAME,COL.DATA_TYPE FROM USER_CONSTRAINTS CI, USER_TAB_COLUMNS COL WHERE CI.TABLE_NAME = COL.TABLE_NAME AND CI.COLUMN_NAME = COL.TABLE_NAME AND CI.TABLE_NAME IN (SELECT TABLE_NAME FROM USER_TAB_COLUMNS C WHERE C.DATA_TYPE = 'NUMBER');
